# Generated by Django 5.0.4 on 2024-05-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('phones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.phones')),
            ],
            options={
                'db_table': 'Android',
            },
        ),
    ]
