# Generated by Django 5.0.4 on 2024-05-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='android',
            old_name='phones',
            new_name='category',
        ),
    ]
