# Generated by Django 5.0.4 on 2024-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_phones_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Android'),
        ),
    ]
