# Generated by Django 5.0.4 on 2024-05-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ios',
            name='category',
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Phone')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'Phone',
            },
        ),
        migrations.DeleteModel(
            name='Android',
        ),
        migrations.DeleteModel(
            name='IOS',
        ),
    ]
