# Generated by Django 5.0.4 on 2024-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_phones_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
